name: Build and Push ComfyUI Worker

on:
  # This workflow runs automatically on any push to the "main" branch
  push:
    branches: [ "main" ]
  # This also allows you to run the workflow manually from the Actions tab on GitHub
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          # IMPORTANT: CHANGE THIS LINE to your Docker Hub username and image name
          tags: bohdanbehmat/comfyui-worker:latest
